name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:          
          wait-on: ${{secrets.FUNCTION_URL}}
          wait-on-timeout: 180
          browser: chrome
          env: CODE=${{secrets.CODE}}
          
      - name: Move test results
        run: mv cypress/results/combined-report.xml junit-reports/

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v2
        with:
            name: junit-test-results
            path: junit-reports/
